-- INSERINDO DADOS NA TABELA DEPARTAMENTO INFORMANDO 
-- COLUNAS E RESPECTIVO CONTEÚDO
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
     VALUES (2, 'MARKETING','MKT');
     
SELECT * FROM T_SIP_DEPARTAMENTO

-- INSERÇÃO COM MANIPULAÇÃO DE DATA/HORA
INSERT INTO T_SIP_PROJETO 
     VALUES (1, 'PROJETO ABC',
             TO_DATE('01/02/2020','DD/MM/YYYY'),
       TO_DATE('15/11/2022','DD/MM/YYYY'));
       
-- CONSULTANDO TODAS AS LINHAS DA TABELA PROJETO
SELECT * FROM T_SIP_PROJETO;

-- INSERÇÃO COM MANIPULAÇÃO DE NÚMEROS DECIMAIS
INSERT INTO T_SIP_FUNCIONARIO
     VALUES (12345,2,'JOÃO DA SILVA XAVIER', 
       TO_DATE('18/03/1985','DD/MM/YYYY'),
       TO_DATE('21/07/2012','DD/MM/YYYY'),
       'AVENIDA PAULISTA, 1900 - 10o. ANDAR', 
             1234.56); -- UTILIZAMOS O PONTO DECIMAL
             
-- CONSULTANDO TODAS AS LINHAS DA TABELA FUNCIONARIO
SELECT * FROM T_SIP_FUNCIONARIO;

-- INSERÇÃO DE VALORES NULOS PARA CAMPOS OPCIONAIS
-- MÉTODO IMPLÍCITO - OMITA A COLUNA DA LISTA DURANTE A INSERÇÃO
INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO)
     VALUES (2, 'PROJETO DEF',
             TO_DATE('19/03/2020','DD/MM/YYYY'));
             
-- INSERÇÃO DE VALORES NULOS PARA CAMPOS OPCIONAIS
-- MÉTODO EXPLICITO - ESPECIFIQUE A PALAVRA-CHAVE NULL, 
-- NA CLÁUSULA VALUES
INSERT INTO T_SIP_PROJETO 
     VALUES (3, 'PROJETO GHI',
             TO_DATE('15/08/2021','DD/MM/YYYY'),
             NULL );
             
-- CONSULTANDO TODAS AS LINHAS DA TABELA PROJETO
SELECT * FROM T_SIP_PROJETO;


-- INSERT DATA VIA SUBQUERY
-- CRIAR UMA TABELA EXEMPLO
-- A TABELA ARMAZENARÁ APENAS PROJETOS FINALIZADOS
CREATE TABLE T_SIP_COPY_PROJETO_FIN
(
    CD_PROJETO          NUMBER(5)       NOT NULL ,
    NM_PROJETO          VARCHAR2(40)    NOT NULL ,
    DT_INICIO           DATE            NOT NULL ,
    DT_TERMINO          DATE            NOT NULL 
);
-- CHAVE PRIMARIA DA TABELA 
   ALTER TABLE T_SIP_COPY_PROJETO_FIN
ADD CONSTRAINT PK_SIP_COPY_PROJETO_FIN
   PRIMARY KEY (CD_PROJETO);
   
SELECT * FROM T_SIP_COPY_PROJETO_FIN;

-- REALIZANDO A CÓPIA DOS DADOS DE UMA TABELA PARA OUTRA
-- UTILIZANDO O COMANDO INSERT E O COMANDO SELECT 
-- SUBCONSULTA OU SUBQUERY)
INSERT INTO T_SIP_COPY_PROJETO_FIN 
       (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
 (SELECT CD_PROJETO, NM_PROJETO, 
         DT_INICIO, DT_TERMINO
    FROM T_SIP_PROJETO
   WHERE DT_TERMINO IS NOT NULL);
   
-- REALIZANDO A CÓPIA DOS DADOS DE UMA TABELA PARA OUTRA
-- UTILIZANDO O COMANDO INSERT E O COMANDO SELECT 
-- SUBCONSULTA OU SUBQUERY)
INSERT INTO T_SIP_COPY_PROJETO_FIN 
            (SELECT * FROM T_SIP_PROJETO
        WHERE DT_TERMINO IS NOT NULL);

-- Both commands did the same thing           
SELECT * FROM T_SIP_COPY_PROJETO_FIN;

--
--
-- Update data
--
--

-- ATUALIZAR DUAS OU MAIS COLUNAS EM UM COMANDO DE ATUALIZACAO
-- ALTERAR O NOME E A DATA DE NASCIMENTO DE UM 
-- FUNCIONARIO ESPECÍFICO
   UPDATE T_SIP_FUNCIONARIO
      SET NM_FUNCIONARIO = 'JOÃO DA SILVA XAVIER DE CAMARGO',
    DT_NASCIMENTO = TO_DATE ('18/05/1985','DD/MM/YYYY')
    WHERE NR_MATRICULA = 12345;
    
-- CONSULTANDO TODAS AS LINHAS DA TABELA FUNCIONÁRIO
SELECT * FROM T_SIP_FUNCIONARIO WHERE NR_MATRICULA = 12345;

-- ATUALIZAR O SALÁRIO DOS FUNCIONARIOS
-- TODOS OS FUNCIONARIOS IRÃO RECEBER UM AUMENTO DE 5%
UPDATE T_SIP_FUNCIONARIO
   SET VL_SALARIO_MENSAL = VL_SALARIO_MENSAL * 1.05;
-- NÃO TEMOS O WHERE (CONDICAO), POIS O AUMENTO 
-- SERÁ APLICADO A TODOS FUNCIONARIOS

-- update with subqueries
-- ATUALIZACAO UTILIZANDO SUBCONSULTA
UPDATE T_SIP_PROJETO
   SET DT_TERMINO = 
       (SELECT DT_TERMINO 
          FROM T_SIP_COPY_PROJETO_FIN
         WHERE CD_PROJETO = 1)
 WHERE DT_TERMINO IS NULL;
 
 -- CONSULTANDO A ALTERAÇÃO REALIZADA
SELECT * FROM T_SIP_PROJETO;


--
--
-- DELETE DATA
--
--

    -- USING DELETE COMMANDS WITHOUT A WHERE QUERY WILL DELETE ALL RECORDS IN THE TABLE/ENTITY
    
-- CONSULTANDO REGISTROS
SELECT * FROM T_SIP_PROJETO;

-- EXCLUSÃO DOS PROJETOS INICIADOS ATÉ 31/12/2020
DELETE FROM T_SIP_PROJETO
      WHERE DT_INICIO <= TO_DATE ('31/12/2020','DD/MM/YYYY');
      
-- CONSULTANDO A EXCLUSÃO REALIZADA
SELECT * FROM T_SIP_PROJETO;


--
-- USING ROLLBACK AND COMMITS
--
--


-- DELEÇÃO DA TABELA PROJETO INTEIRA, 
-- SEM EFETIVAÇÃO DA TRANSAÇÃO
DELETE FROM T_SIP_PROJETO;

-- CONSULTANDO A EXCLUSÃO REALIZADA
SELECT * FROM T_SIP_PROJETO;

-- EXEMPLO COM ROLLBACK
ROLLBACK;

-- VISUALIZAÇÃO DA DELEÇÃO DESCARTADA
SELECT * FROM T_SIP_PROJETO;

