-- SELECT [ DISTINCT | ALL] { * | coluna  [, coluna, â€¦ ] }
--   FROM tabela
--  WHERE condiÃ§Ã£o
--     ORDER BY coluna [, coluna, ...]

-- CONSULTANDO TODAS AS LINHAS E COLUNAS DA TABELA FUNCIONARIO
SELECT * FROM T_SIP_FUNCIONARIO;

-- Especificando as colunas que deseja consultar e recuperando -- todas as linhas da tabela FUNCIONARIO
SELECT NR_MATRICULA, NM_FUNCIONARIO, VL_SALARIO_MENSAL
  FROM T_SIP_FUNCIONARIO;
  
-- Especificando as colunas que deseja consultar e filtrando --- as linhas da tabela FUNCIONARIO.
SELECT NR_MATRICULA, CD_DEPTO, 
       NM_FUNCIONARIO, VL_SALARIO_MENSAL
  FROM T_SIP_FUNCIONARIO
 WHERE CD_DEPTO = 3;
 
 
 -- RECUPERANDO OS DEPARTAMENTOS (SEM REPETIÇÃO) QUE POSSUEM 
-- FUNCIONARIOS
SELECT DISTINCT CD_DEPTO FROM T_SIP_FUNCIONARIO;
-- OU
SELECT UNIQUE CD_DEPTO FROM T_SIP_FUNCIONARIO;

-- EXEMPLO DE CONSULTA UTILIZANDO OPERADORES ARITMÉTICOS
SELECT NR_MATRICULA, NM_FUNCIONARIO, 
       VL_SALARIO_MENSAL,
       VL_SALARIO_MENSAL * 1.05
  FROM T_SIP_FUNCIONARIO;
  
  -- EXEMPLOS DE APELIDOS DE COLUNAS com ALIAS/ AS
SELECT NR_MATRICULA, 
 NM_FUNCIONARIO FUNCIONARIO, 
 VL_SALARIO_MENSAL "SALÁRIO MENSAL",
 VL_SALARIO_MENSAL * 1.05 AS "SALÁRIO REAJUSTADO"
  FROM T_SIP_FUNCIONARIO;
  
  
-- APRESENTANDO RESULTADOS DE FORMA ORDENADA
-- ORDER BY ASC
  SELECT CD_DEPTO, NM_DEPTO
    FROM T_SIP_DEPARTAMENTO
ORDER BY NM_DEPTO;

-- APRESENTANDO RESULTADOS DE FORMA ORDENADA
-- ORDER BY DESC
  SELECT CD_DEPTO, NM_DEPTO
    FROM T_SIP_DEPARTAMENTO
ORDER BY NM_DEPTO DESC;


-- MUITO LEGAL MUITOOOOOOO
-- APRESENTANDO RESULTADOS DE FORMA ORDENADA
-- ORDER BY UTILIZANDO NÚMEROS QUE REPRESENTAM 
-- A POSIÇÃO DAS COLUNAS NO SELECT
  SELECT NR_MATRICULA, CD_DEPTO, 
   NM_FUNCIONARIO, VL_SALARIO_MENSAL  
    FROM T_SIP_FUNCIONARIO 
ORDER BY 2 DESC, 4 ASC;


-- APRESENTANDO RESULTADOS DE FORMA ORDENADA
-- ORDER BY UTILIZANDO O APELIDO DAS COLUNAS
  SELECT NR_MATRICULA        "MATRICULA", 
         NM_FUNCIONARIO      "NOME ",
         VL_SALARIO_MENSAL   "SALÁRIO MENSAL",
         VL_SALARIO_MENSAL * 1.05 "SALÁRIO REAJUSTADO"
    FROM T_SIP_FUNCIONARIO 
ORDER BY "SALÁRIO REAJUSTADO" DESC;

--
-- FILTERS
--

-- FILTRANDO POR NÚMEROS
SELECT NR_MATRICULA, NM_FUNCIONARIO, VL_SALARIO_MENSAL
  FROM T_SIP_FUNCIONARIO
 WHERE VL_SALARIO_MENSAL < 1500.50;
 
 
-- FILTRANTO POR TEXTO (CADEIA DE CARACTERES)
SELECT NR_MATRICULA, NM_FUNCIONARIO
  FROM T_SIP_FUNCIONARIO 
 WHERE NM_FUNCIONARIO = 'THIAGO DE ALMEIDA';
 
 -- UTILIZANDO A CONVERSÃO DE TEXTO
SELECT NR_MATRICULA, NM_FUNCIONARIO
  FROM T_SIP_FUNCIONARIO
 WHERE UPPER(NM_FUNCIONARIO) = 'JOAO DA SILVA'; 
-- OU 
 SELECT NR_MATRICULA, NM_FUNCIONARIO
  FROM T_SIP_FUNCIONARIO
 WHERE LOWER(NM_FUNCIONARIO) = 'joao da silva';
 
 -- FILTRANDO POR DATA
SELECT NR_MATRICULA, NM_FUNCIONARIO, DT_ADMISSAO
  FROM T_SIP_FUNCIONARIO
 WHERE DT_ADMISSAO >= TO_DATE('01/08/2015','DD/MM/YYYY');
 
-- 
-- LOGIC OPERATORS
-- 

-- OPERADOR LOGICO AND -> PRECISA ATENDER AS DUAS CONDIÇÕES 
-- PARA RECUPERAR OS VALORES
SELECT NR_MATRICULA, NM_FUNCIONARIO, CD_DEPTO, DT_ADMISSAO
  FROM T_SIP_FUNCIONARIO
 WHERE DT_ADMISSAO >= TO_DATE('01/08/2015','DD/MM/YYYY') 
       AND CD_DEPTO = 3;
       
-- OPERADOR LOGICO OR -> PRECISA ANTENDER QUALQUER UMA 
-- DAS CONDIÇÕES PARA RECUPERAR OS VALORES
SELECT NR_MATRICULA, NM_FUNCIONARIO, 
       CD_DEPTO, VL_SALARIO_MENSAL
  FROM T_SIP_FUNCIONARIO
 WHERE CD_DEPTO = 4 
 OR VL_SALARIO_MENSAL > 3000;
 
 -- OPERADOR NOT
SELECT NR_MATRICULA, NM_FUNCIONARIO, 
 CD_DEPTO, VL_SALARIO_MENSAL
  FROM T_SIP_FUNCIONARIO
 WHERE NOT CD_DEPTO = 4;
 
-- 
-- SPECIAL OPERATORS
--

-- OPERADOR BETWEEN
SELECT NR_MATRICULA, NM_FUNCIONARIO, 
 CD_DEPTO, VL_SALARIO_MENSAL  
FROM   T_SIP_FUNCIONARIO 
WHERE  VL_SALARIO_MENSAL BETWEEN 1000 AND 2500;


-- OPERADOR BETWEEN
SELECT NR_MATRICULA, NM_FUNCIONARIO, 
 CD_DEPTO, DT_ADMISSAO  
FROM   T_SIP_FUNCIONARIO 
WHERE  DT_ADMISSAO BETWEEN TO_DATE('01/01/2013','DD/MM/YYYY')
       AND  TO_DATE('30/12/2015','DD/MM/YYYY');
       
-- OPERADOR IN
SELECT NR_MATRICULA, NM_FUNCIONARIO, CD_DEPTO
  FROM   T_SIP_FUNCIONARIO
 WHERE  CD_DEPTO IN (2,3);
 
 -- OPERADOR NOT IN
SELECT NR_MATRICULA, NM_FUNCIONARIO, CD_DEPTO
FROM   T_SIP_FUNCIONARIO
WHERE  CD_DEPTO NOT IN (1,3, 5);

-- OPERADOR IN
SELECT  NR_MATRICULA ,      
  DT_ADMISSAO ,
  VL_SALARIO_MENSAL 
FROM    T_SIP_FUNCIONARIO
WHERE   TO_CHAR(DT_ADMISSAO,'YYYY') IN ('2012','2014');

-- OPERADOR IS NOT NULL
SELECT CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO
  FROM T_SIP_PROJETO
 WHERE DT_TERMINO IS NOT NULL;
 
 -- OPERADOR IS NULL
SELECT CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO
  FROM T_SIP_PROJETO
 WHERE DT_TERMINO IS NULL;
 
-- like is like regex
 -- OPERADOR LIKE
SELECT CD_DEPTO, NM_DEPTO
  FROM T_SIP_DEPARTAMENTO
 WHERE NM_DEPTO LIKE 'FINA%';
 
 -- OPERADOR LIKE
SELECT CD_DEPTO, NM_DEPTO
FROM   T_SIP_DEPARTAMENTO
WHERE  NM_DEPTO LIKE '_A%';

-- OPERADOR LIKE
SELECT CD_DEPTO, NM_DEPTO
FROM   T_SIP_DEPARTAMENTO
WHERE  NM_DEPTO LIKE '___UR%';

-- MULTIPLE FILTERS
-- Exemplo utilizando vários operadores
SELECT 	NR_MATRICULA   ,
         CD_DEPTO       ,
         NM_FUNCIONARIO ,
         DT_NASCIMENTO  ,
         DT_ADMISSAO    ,
         VL_SALARIO_MENSAL
  FROM 	T_SIP_FUNCIONARIO
 WHERE   DT_NASCIMENTO 
             BETWEEN 
                 TO_DATE('01/01/1980','DD/MM/YYYY')  
             AND
                 TO_DATE('30/12/2010','DD/MM/YYYY')                   
         AND
          DT_ADMISSAO > TO_DATE('01/01/2013','DD/MM/YYYY')  
         AND VL_SALARIO_MENSAL < 2300 
         AND NOT CD_DEPTO = 3 ;
         
-- CONCAT STRING AAAAA
-- EXIBIR O TEXTO: "O FUNCIONARIO <NOME> FOI 
-- ADMITIDO EM <DATA ADMISSAO>"
SELECT NR_MATRICULA,
 'O FUNCIONARIO ' || 
 NM_FUNCIONARIO ||
 ', FOI ADMITIDO EM: ' || 
 DT_ADMISSAO AS "CONCAT TEXT"
  FROM T_SIP_FUNCIONARIO;
  
  
-- LIMIT QUERY RESULTS
-- RESTRINGINDO A QUANTIDADE DE LINHAS RECUPERADAS 
-- DURANTE A CONSULTA
SELECT    NR_MATRICULA ,
    CD_DEPTO ,
    DT_ADMISSAO ,
    VL_SALARIO_MENSAL ,
    (VL_SALARIO_MENSAL * 12) "SALÁRIO ANUAL"
  FROM   T_SIP_FUNCIONARIO
 WHERE  ROWNUM <= 2;
 
 
-- TOP-N
-- PARA EXIBIR OS NOMES E OS SALÁRIOS DOS 
-- TRÊS FUNCIONÁRIOS MAIS BEM REMUNERADOS 
-- DA TABELA FUNCIONARIO.
SELECT  ROWNUM as RANK , 
               NM_FUNCIONARIO , 
               VL_SALARIO_MENSAL
FROM 
    (    SELECT NM_FUNCIONARIO ,
                VL_SALARIO_MENSAL
           FROM T_SIP_FUNCIONARIO
       ORDER BY VL_SALARIO_MENSAL DESC
    )
WHERE ROWNUM <= 3;


-- NATIONAL LANGUAGE SUPORT PARAMS
-- VISUALIZAR A CONFIGURAÇÃO ATUAL DOS ATRIBUTOS NLS
-- ATUAIS PARA A SUA SESSÃO
SELECT * FROM V$NLS_PARAMETERS;

-- Para alterar o formato de exibição de uma data 
-- é utilizado a sintaxe:
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

-- CONSULTA A TABELA PROJETO
SELECT * FROM T_SIP_PROJETO;

--Para alterar o idioma da data de exibição 
-- é utilizado a sintaxe:
ALTER SESSION SET NLS_DATE_LANGUAGE = 'PORTUGUESE';

-- CONSULTA A DATA SO SERVIDOR
SELECT SYSDATE,
       TO_CHAR(SYSDATE, 'MONTH')    
  FROM DUAL;
