-- EXEMPLO FULL OUTER JOIN - PADRÃO SQL/99
SELECT EC.CD_EMPRESA_CONV,
       EC.DS_RAZAO_SOCIAL,
       M.NR_MATRICULA_ALUNO,
       M.CD_ALUNO
  FROM T_SCA_EMPRESA_CONV EC FULL OUTER JOIN T_SCA_MATRICULA M
       ON (EC.CD_EMPRESA_CONV = M.CD_EMPRESA_CONV);
       
-- EXEMPLO COM FULL OUTER JOIN - PADRÃO SQL/99 -  
-- COM VALIDAÇÃO DOS RESULTADOS NULOS
SELECT EC.CD_EMPRESA_CONV,
 EC.DS_RAZAO_SOCIAL,
 M.NR_MATRICULA_ALUNO,
 M.CD_ALUNO
FROM T_SCA_EMPRESA_CONV EC FULL OUTER JOIN T_SCA_MATRICULA M
 ON (EC.CD_EMPRESA_CONV = M.CD_EMPRESA_CONV) 
 WHERE EC.CD_EMPRESA_CONV IS NULL OR
       M.NR_MATRICULA_ALUNO IS NULL;
    
    
-- EXEMPLO FULL OUTER JOIN - PADRÃO SQL/99 
-- CLÁUSULA USING
SELECT CD_EMPRESA_CONV,
 EC.DS_RAZAO_SOCIAL,
 M.NR_MATRICULA_ALUNO,
 M.CD_ALUNO
FROM T_SCA_EMPRESA_CONV EC FULL OUTER JOIN T_SCA_MATRICULA M
       USING (CD_EMPRESA_CONV);
       
