-- SELECT tabela1.coluna, tabela2.coluna
-- FROM tabela1
-- 	[CROSS JOIN tabela2] |
-- 	[NATURAL JOIN tabela2] |
-- 	[JOIN tabela2 USING (nome_coluna)] |
-- 	[JOIN tabela2
-- 	ON(tabela1.nome_coluna = tabela2.nome_coluna)] |
-- 	[LEFT|RIGHT|FULL OUTER JOIN tabela2
-- 	ON (tabela1.nome_coluna = tabela2.nome_coluna)];

-- Exemplo de consulta com qualificador de nomes
SELECT   T_SIP_FUNCIONARIO.NR_MATRICULA ,
         T_SIP_FUNCIONARIO.CD_DEPTO     ,
         T_SIP_FUNCIONARIO.DT_ADMISSAO  ,
         T_SIP_FUNCIONARIO.VL_SALARIO_MENSAL
  FROM   T_SIP_FUNCIONARIO ;
  
-- Exemplo de consulta a duas tabelas sem ALIAS
SELECT T_SIP_FUNCIONARIO.NM_FUNCIONARIO ,
       T_SIP_FUNCIONARIO.CD_DEPTO       ,
       T_SIP_DEPARTAMENTO.NM_DEPTO
  FROM T_SIP_DEPARTAMENTO INNER JOIN T_SIP_FUNCIONARIO 
    ON T_SIP_DEPARTAMENTO.CD_DEPTO = T_SIP_FUNCIONARIO.CD_DEPTO;
    
-- Exemplo de consulta a duas tabelas com ALIAS
SELECT F.NM_FUNCIONARIO ,
       F.CD_DEPTO       ,
       D.NM_DEPTO
  FROM T_SIP_DEPARTAMENTO D INNER JOIN T_SIP_FUNCIONARIO F
       ON (D.CD_DEPTO = F.CD_DEPTO);
       
       
-- UTILIZANDO O PADRÃO ANSI SQL/99
-- CROSS JOIN 
SELECT * FROM T_SIP_DEPARTAMENTO 
       CROSS JOIN T_SIP_FUNCIONARIO;
       
-- EXEMPLO - INNER JOIN – Padrão SQL/99
  SELECT F.NR_MATRICULA, F.CD_DEPTO,
         D.NM_DEPTO, F.NM_FUNCIONARIO   
    FROM T_SIP_DEPARTAMENTO D INNER JOIN T_SIP_FUNCIONARIO  F 
         ON ( D.CD_DEPTO = F.CD_DEPTO )
ORDER BY D.NM_DEPTO;

-- EXEMPLO - INNER JOIN com a cláusula USING
  SELECT F.NR_MATRICULA, 
         CD_DEPTO,
         D.NM_DEPTO, F.NM_FUNCIONARIO 
    FROM T_SIP_DEPARTAMENTO D INNER JOIN T_SIP_FUNCIONARIO  F
         USING ( CD_DEPTO )
ORDER BY NM_DEPTO;

--
-- Multiple tables join
-- EXEMPLO - INNER JOIN – Padrão SQL/99
  SELECT F.NR_MATRICULA, F.NM_FUNCIONARIO,
         P.NM_PROJETO,
         I.DT_ENTRADA,I.DT_SAIDA 
    FROM T_SIP_PROJETO P INNER JOIN T_SIP_IMPLANTACAO I
         ON ( P.CD_PROJETO = I.CD_PROJETO )
         INNER JOIN  T_SIP_FUNCIONARIO  F 
         ON ( F.NR_MATRICULA = I.NR_MATRICULA )
ORDER BY F.NM_FUNCIONARIO ;

-- EXEMPLO COM INNER JOIN - PADRÃO SQL/99 -  
-- CLÁUSULA USING
  SELECT NR_MATRICULA, F.NM_FUNCIONARIO,
         P.NM_PROJETO,
         I.DT_ENTRADA,I.DT_SAIDA 
    FROM T_SIP_PROJETO P INNER JOIN T_SIP_IMPLANTACAO I
         USING ( CD_PROJETO )
         INNER JOIN  T_SIP_FUNCIONARIO  F 
         USING ( NR_MATRICULA )
ORDER BY F.NM_FUNCIONARIO ;


--
-- OUTER AND EQUIJOINS
--

-- LEFT JOIN
-- EXEMPLO LEFT OUTER JOIN - PADRÃO SQL/99
SELECT   P.CD_PROJETO, P.NM_PROJETO, P.DT_INICIO,
               I.NR_MATRICULA, I.DT_ENTRADA         
  FROM   T_SIP_PROJETO P LEFT OUTER JOIN T_SIP_IMPLANTACAO I
         ON ( P.CD_PROJETO = I.CD_PROJETO );
         
-- EXEMPLO COM LEFT OUTER JOIN - PADRÃO SQL/99 -  
-- COM VALIDAÇÃO DOS RESULTADOS NULOS
SELECT   P.CD_PROJETO, P.NM_PROJETO, P.DT_INICIO,
         I.NR_MATRICULA, I.DT_ENTRADA          
  FROM   T_SIP_PROJETO P LEFT OUTER JOIN T_SIP_IMPLANTACAO I
         ON ( P.CD_PROJETO = I.CD_PROJETO )
 WHERE   I.CD_PROJETO IS NULL ;
 
 -- EXEMPLO LEFT OUTER JOIN - PADRÃO SQL/99 
-- CLÁUSULA USING
SELECT   CD_PROJETO, P.NM_PROJETO, P.DT_INICIO,
         I.NR_MATRICULA, I.DT_ENTRADA         
  FROM   T_SIP_PROJETO P LEFT OUTER JOIN T_SIP_IMPLANTACAO I
         USING ( CD_PROJETO );
         
-- RIGHT JOIJN
-- EXEMPLO RIGHT OUTER JOIN - PADRÃO SQL/99
SELECT F.NR_MATRICULA,
       I.CD_PROJETO, I.DT_ENTRADA,I.DT_SAIDA
FROM  T_SIP_IMPLANTACAO I RIGHT OUTER JOIN T_SIP_FUNCIONARIO F
         ON ( F.NR_MATRICULA = I.NR_MATRICULA );
         
-- EXEMPLO COM RIGHT OUTER JOIN - PADRÃO SQL/99 -  
-- COM VALIDAÇÃO DOS RESULTADOS NULOS
SELECT  F.NR_MATRICULA,
        I.CD_PROJETO, I.DT_ENTRADA,I.DT_SAIDA
FROM  T_SIP_IMPLANTACAO I RIGHT OUTER JOIN T_SIP_FUNCIONARIO F
        ON ( F.NR_MATRICULA = I.NR_MATRICULA )
 WHERE  I.NR_MATRICULA IS NULL ;
 
 -- EXEMPLO RIGHT OUTER JOIN - PADRÃO SQL/99 
-- CLÁUSULA USING
SELECT NR_MATRICULA,
       I.CD_PROJETO, I.DT_ENTRADA,I.DT_SAIDA
FROM  T_SIP_IMPLANTACAO I RIGHT OUTER JOIN T_SIP_FUNCIONARIO F
      USING ( NR_MATRICULA );